export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_ERROR_RESET = "USER_LOGIN_ERROR_RESET";

export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_ERROR = "FETCH_CURRENT_USER_ERROR";

export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";
export const USER_SIGNUP_ERROR_RESET = "USER_SIGNUP_ERROR_RESET";

export const VERIFY_USER_EMAIL = "VERIFY_USER_EMAIL";
export const VERIFY_USER_EMAIL_SUCCESS = "VERIFY_USER_EMAIL_SUCCESS";
export const VERIFY_USER_EMAIL_ERROR = "VERIFY_USER_EMAIL_ERROR";

export const USER_SIGNOUT = "USER_SIGNOUT";
export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS";
export const USER_SIGNOUT_ERROR = "USER_SIGNOUT_ERROR";

export const SEND_USER_PASSWORD_RESET_LINK = "SEND_USER_PASSWORD_RESET_LINK";
export const SEND_USER_PASSWORD_RESET_LINK_SUCCESS = "SEND_USER_PASSWORD_RESET_LINK_SUCCESS";
export const SEND_USER_PASSWORD_RESET_LINK_ERROR = "SEND_USER_PASSWORD_RESET_LINK_ERROR";
export const SEND_USER_PASSWORD_RESET_LINK_ERROR_RESET = "SEND_USER_PASSWORD_RESET_LINK_ERROR_RESET";

export const RESET_USER_PASSWORD = "RESET_USER_PASSWORD";
export const RESET_USER_PASSWORD_SUCCESS = "RESET_USER_PASSWORD_SUCCESS";
export const RESET_USER_PASSWORD_ERROR = "RESET_USER_PASSWORD_ERROR";

export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_ERROR = "UPDATE_USER_PASSWORD_ERROR";

export const UPDATE_USER_2FA = "UPDATE_USER_2FA";
export const UPDATE_USER_2FA_SUCCESS = "UPDATE_USER_2FA_SUCCESS";
export const UPDATE_USER_2FA_ERROR = "UPDATE_USER_2FA_ERROR";

export const GET_USER_REFERRAL = "GET_USER_REFERRAL";
export const GET_USER_REFERRAL_SUCCESS = "GET_USER_REFERRAL_SUCCESS";
export const GET_USER_REFERRAL_ERROR = "GET_USER_REFERRAL_ERROR";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_ERROR = "UPDATE_USER_PROFILE_ERROR";

export const GET_SUPPORTED_CURRENCIES = "GET_SUPPORTED_CURRENCIES";
export const GET_SUPPORTED_CURRENCIES_SUCCESS = "GET_SUPPORTED_CURRENCIES_SUCCESS";
export const GET_SUPPORTED_CURRENCIES_ERROR = "GET_SUPPORTED_CURRENCIES_ERROR";

export const UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_ERROR = "UPLOAD_DOCUMENT_ERROR";
export const UPLOAD_DOCUMENT_CLEAR_ERROR = "UPLOAD_DOCUMENT_CLEAR_ERROR";

export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS";
export const DELETE_DOCUMENT_ERROR = "DELETE_DOCUMENT_ERROR";

export const GET_KYC_TITLE = "GET_KYC_TITLE";
export const SEND_KYC_DATA = "SEND_KYC_DATA";
export const SEND_KYC_DATA_SUCCESS = "SEND_KYC_DATA_SUCCESS";
export const SEND_KYC_DATA_ERROR = "SEND_KYC_DATA_ERROR";
export const CHANGE_KYC_NOTIFICATION = "CHANGE_KYC_NOTIFICATION";

export const VERIFICATION_CHECKING = "VERIFICATION_CHECKING";
export const VERIFICATION_CHECKING_SUCCESS = "VERIFICATION_CHECKING_SUCCESS";
export const VERIFICATION_CHECKING_ERROR = "VERIFICATION_CHECKING_ERROR";

export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const GET_DOCUMENTS_SUCCESS = "GET_DOCUMENTS_SUCCESS";
export const GET_DOCUMENTS_ERROR = "GET_DOCUMENTS_ERROR";

export const SELECT_CURRENCY = "SELECT_CURRENCY";

export const GET_CURRENCY_QUOTE = "GET_CURRENCY_QUOTE";
export const GET_CURRENCY_QUOTE_SUCCESS = "GET_CURRENCY_QUOTE_SUCCESS";
export const GET_CURRENCY_QUOTE_ERROR = "GET_CURRENCY_QUOTE_ERROR";

export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_ERROR = "CREATE_PAYMENT_ERROR";
export const CREATE_PAYMENT_ERROR_RESET = "CREATE_PAYMENT_ERROR_RESET";

export const REMOVE_PAYMENT = "REMOVE_PAYMENT";
export const REMOVE_PAYMENT_SUCCESS = "REMOVE_PAYMENT_SUCCESS";
export const REMOVE_PAYMENT_ERROR = "REMOVE_PAYMENT_ERROR";
export const REMOVE_PAYMENT_ERROR_RESET = "REMOVE_PAYMENT_ERROR_RESET";

export const TRACK_PAYMENT = "TRACK_PAYMENT";
export const TRACK_PAYMENT_SUCCESS = "TRACK_PAYMENT_SUCCESS";
export const TRACK_PAYMENT_ERROR = "TRACK_PAYMENT_ERROR";

export const TOKEN_BUYS = "TOKEN_BUYS";
export const TOKEN_BUYS_SUCCESS = "TOKEN_BUYS_SUCCESS";
export const TOKEN_BUYS_ERROR = "TOKEN_BUYS_ERROR";
export const TOKEN_BUYS_ERROR_RESET = "TOKEN_BUYS_ERROR_RESET";

export const GET_PAYMENTS = "GET_PAYMENTS";
export const GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";
export const GET_PAYMENTS_ERROR = "GET_PAYMENTS_ERROR";

export const GET_WALLETS = "GET_WALLETS";
export const GET_WALLETS_SUCCESS = "GET_WALLETS_SUCCESS";
export const GET_WALLETS_ERROR = "GET_WALLETS_ERROR";

export const CREATE_WALLET = "CREATE_WALLET";
export const CREATE_WALLET_SUCCESS = "CREATE_WALLET_SUCCESS";
export const CREATE_WALLET_ERROR = "CREATE_WALLET_ERROR";

export const GET_TOKEN_BUYS = 'GET_TOKEN_BUYS';
export const GET_TOKEN_BUYS_SUCCESS = 'GET_TOKEN_BUYS_SUCCESS';
export const GET_TOKEN_BUYS_ERROR = 'GET_TOKEN_BUYS_ERROR';
export const GET_TOKEN_BUYS_ERROR_RESET = 'GET_TOKEN_BUYS_ERROR_RESET';

export const GET_TOKEN_SALES = 'GET_TOKEN_SALES';
export const GET_TOKEN_SALES_SUCCESS = 'GET_TOKEN_SALES_SUCCESS';
export const GET_TOKEN_SALES_ERROR = 'GET_TOKEN_SALES_ERROR';

export const GET_TOKEN_SALES_MILESTONES = 'GET_TOKEN_SALES_MILESTONES';
export const GET_TOKEN_SALES_MILESTONES_SUCCESS = 'GET_TOKEN_SALES_MILESTONES_SUCCESS';
export const GET_TOKEN_SALES_MILESTONES_ERROR = 'GET_TOKEN_SALES_MILESTONES_ERROR';

export const GET_PRICES = 'GET_PRICES';
export const GET_PRICES_SUCCESS = 'GET_PRICES_SUCCESS';
export const GET_PRICES_ERROR = 'GET_PRICES_ERROR';

export const SEND_ORDER = 'SEND_ORDER';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_ERROR = 'SEND_ORDER_ERROR';

export const GET_BALANCE_OVERTIME = 'GET_BALANCE_OVERTIME';
export const GET_BALANCE_OVERTIME_SUCCESS = 'GET_BALANCE_OVERTIME_SUCCESS';
export const GET_BALANCE_OVERTIME_ERROR = 'GET_BALANCE_OVERTIME_ERROR';

export const GET_WALLETS_REAL_TIME_SUCCESS = 'GET_WALLETS_REAL_TIME_SUCCESS';
export const GET_TOKEN_SALES_REAL_TIME_SUCCESS = 'GET_TOKEN_SALES_REAL_TIME_SUCCESS';

export const FLASHSALE_TOKEN_SUCCESS = 'FLASHSALE_TOKEN_SUCCESS';
export const FLASHSALE_TOKEN_FAIL = 'FLASHSALE_TOKEN_FAIL';

export const TWO_FACTOR_AUTH_START = 'TWO_FACTOR_AUTH_START';
export const TWO_FACTOR_AUTH_END = 'TWO_FACTOR_AUTH_END';

export const AIRDROP_SUCCESS = 'AIRDROP_SUCCESS';
export const AIRDROP_FAIL = 'AIRDROP_FAIL';

export const GET_CANDLE_HISTORY = 'GET_CANDLE_HISTORY';
export const GET_CANDLE_HISTORY_SUCCESS = 'GET_CANDLE_HISTORY_SUCCESS';
export const GET_CANDLE_HISTORY_ERROR = 'GET_CANDLE_HISTORY_ERROR';

export const DISABLE_WALLET = 'DISABLE_WALLET';
export const DISABLE_WALLET_SUCCESS = 'DISABLE_WALLET_SUCCESS';
export const DISABLE_WALLET_ERROR = 'DISABLE_WALLET_ERROR';

export const GET_OPEN_ORDERS = 'GET_OPEN_ORDERS';
export const GET_OPEN_ORDERS_SUCCESS = 'GET_OPEN_ORDERS_SUCCESS';
export const GET_OPEN_ORDERS_ERROR = 'GET_OPEN_ORDERS_ERROR';

export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS';
export const GET_ORDER_HISTORY_ERROR = 'GET_ORDER_HISTORY_ERROR';

export const GET_TRADE_HISTORY = 'GET_TRADE_HISTORY';
export const GET_TRADE_HISTORY_SUCCESS = 'GET_TRADE_HISTORY_SUCCESS';
export const GET_TRADE_HISTORY_ERROR = 'GET_TRADE_HISTORY_ERROR';

export const GET_BOOK_DATA = 'GET_BOOK_DATA';
export const GET_BOOK_DATA_SUCCESS = 'GET_BOOK_DATA_SUCCESS';
export const GET_BOOK_DATA_ERROR = 'GET_BOOK_DATA_ERROR';

export const GET_BOOK_UPDATES = 'GET_BOOK_UPDATES';
export const GET_BOOK_UPDATES_SUCCESS = 'GET_BOOK_UPDATES_SUCCESS';
export const GET_BOOK_UPDATES_ERROR = 'GET_BOOK_UPDATES_ERROR';

export const SET_OPT_IN = "SET_OPT_IN";
export const SET_OPT_IN_SUCCESS = "SET_OPT_IN_SUCCESS";
export const SET_OPT_IN_ERROR = "SET_OPT_IN_ERROR";